// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAskWf9BOzcJjLFgpbZuDyxPOkmuSkfg74',
    appId: '1:90391184253:web:c8bfb915f2b58a7a2a4214',
    messagingSenderId: '90391184253',
    projectId: 'freek-personal-app',
    authDomain: 'freek-personal-app.firebaseapp.com',
    storageBucket: 'freek-personal-app.firebasestorage.app',
    measurementId: 'G-2QS6P87Y95',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgDVo2ILFBr-6Bt8FQjJN2Qs9OBo5UMnM',
    appId: '1:90391184253:android:fac4d1149a81b41c2a4214',
    messagingSenderId: '90391184253',
    projectId: 'freek-personal-app',
    storageBucket: 'freek-personal-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9WlmJBq21hAHv7IgEqNYFa6-7mmHxpOk',
    appId: '1:90391184253:ios:e1584ddc3c7550312a4214',
    messagingSenderId: '90391184253',
    projectId: 'freek-personal-app',
    storageBucket: 'freek-personal-app.firebasestorage.app',
    iosBundleId: 'nl.freekvandeven.personalApp',
  );
}
